spring:
  application:
    name: CRC
  profiles:
    active: test
  thymeleaf:
    check-template-location: false
  ai:
    openai:
      api-key: ''

server:
  port: 8085

azure:
  storage:
    account-name: "crc"
    account-key: ""
    connection-string: ""

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    supported-submit-methods: { "get", "put", "post", "delete", "options", "head", "patch", "trace" }
  api-docs:
    enabled: true

